### ISSUE TITLE
CVC check doesn't work against a validmastercard

### ISSUE THREAD

**Issue by trollboy** [inacho/php-credit-card-validator#1]
Used my mastercard to test, has a cvc w 2 digits over 5

**Comment by inacho** [comment]
The CVC of MasterCard always have a length of 3 digits. For example: 123
What is the length of your CVC?

**Comment by trollboy** [comment]
3 digits total

**Comment by inacho** [comment]
It should work fine. The CVC is only validated against the length defined in the rules.

This code will output `bool(true)`:

``` php
var_dump(CreditCard::validCvc('123', 'mastercard'));
```

Check that you CVC don't contain spaces with the [trim](http://php.net/manual/en/function.trim.php) function

**Comment by trollboy** [comment]
Verified that I'm running trim  "179" fails still
